name: Cálculo de Fechas Dinámicas

on:
  schedule:
    - cron: '0 7 * * *' # 2:00 AM Bogotá (7:00 AM UTC)
  workflow_dispatch: # Habilita la ejecución manual

jobs:
  calcular-fechas:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment variables
      env:
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: echo "Environment variables set."

    - name: Verificar conexión a la base de datos
      env:
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: |
        python -c "
        import psycopg2
        try:
            conn = psycopg2.connect('${{ secrets.DATABASE_PATH }}')
            print('Conexión a la base de datos exitosa')
            conn.close()
        except Exception as e:
            print(f'Error al conectar a la base de datos: {e}')
            raise e
        "
    - name: Ejecutar cálculo de fechas dinámicas
      env:
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: |
        python -c "from model.job import TareasProgramadasJuridico; TareasProgramadasJuridico().calcular_y_actualizar_fechas_dinamicas()"
